#없어진 기록 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS AS OUTS
WHERE ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_INS)

#있었는데요 없었습니다
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS AS INS, ANIMAL_OUTS AS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID AND INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME

#우유와 요거트가 담긴 장바구니
SELECT DISTINCT MCART.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'MILK') AS MCART,(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'YOGURT') AS YCART
WHERE MCART.CART_ID = YCART.CART_ID
ORDER BY MCART.CART_ID

#오랜 기간 보호한 동물(1)
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN(SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3

#오랜 기간 보호한 동물(2)
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS, ANIMAL_OUTS AS OUTS
WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC
LIMIT 2

#헤비 유저가 소유한 장소
SELECT *
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID)>1
)
ORDER BY ID

#보호소에서 중성화한 동물
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE NOT LIKE '%SPAYED%' AND SEX_UPON_INTAKE NOT LIKE '%Neutered%' AND ANIMAL_ID IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE '%SPAYED%' OR SEX_UPON_OUTCOME LIKE '%Neutered%')
ORDER BY ANIMAL_ID

#입양 시각 구하기(2)
SET @hour := -1;
SELECT (@hour := @hour + 1) as HOUR,
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) as COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23
